import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Container, Row, Col, Button, Card } from 'react-bootstrap'

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon preconnect" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <iframe rel="preconnect" title="backgroun dvisual" src="../index.html" overflow="hidden" border="none" height="800vh" width="100%" display="flex"></iframe>
      </main>

      <footer className={styles.footer}>
          Meow
      </footer>
    </Container>
  )
}
